# Site settings
title:OvO
email:email
description: > # this means to ignore newlines until "baseurl:"
baseurl: "wwwwwww" # the subpath of your site, e.g. /blog/
url: "https://laguzfable.github.io/witchclubweb/" # the base hostname & protocol for your site

twitter_username:laguzfable
github_username:laguzfable

# Build settings
markdown: kramdown
